---
title: "Week 4 part 1 CI and TT"
author: "Joaquin Meckler"
date: "10/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
```


## 1. confidence intervals

```{r}
otter_length<- c(38,41,50,27,32,41,48,60,43)

t.test(otter_length)
```

## t-test(1-sample t-test)

claim: mean otter length is 50 inches

```{r}
otter_test<-t.test(x= otter_length, mu= 50)
otter_test
```

## two-sample t-test

```{r}
desert_bighorns<- c(32,44,18,26,50,33,42,20)
sierra_bighorns<-c(28,31,40,42,26,29,31)

t.test(x=desert_bighorns, y=sierra_bighorns)
```


## two-sample t-test


```{r}
compact_suv <- mpg %>% 
  filter(class %in% c("compact", "suv"))
```


## exploratory data viz
histograms

```{r}
ggplot(data=compact_suv, aes(x=cty))+
  geom_histogram(bins=15)+
  facet_wrap(~class)
```

## quantile-quantile plot

```{r}
ggplot(data=compact_suv, aes(sample=cty))+
         geom_qq()+
  facet_wrap(~class)
```

## descriptive statistics

```{r}
car_stats<-compact_suv %>% 
  group_by(class) %>% 
  summarize(mean_city=mean(cty),
            sd_city=sd(cty),
            n=n())

car_stats
```

## 2-sample t-test

# create vectors with observations for each sample


```{r}
compact_sample<-compact_suv %>% 
  filter(class=="compact") %>% 
  pull(cty)

suv_sample<-compact_suv %>% 
  filter(class=="suv") %>% 
  pull(cty)

t.test(x=compact_sample, suv_sample)
```











